name: "Merge Docker digests"
description: "Combine per-platform bake metadata into multi-arch manifests."

inputs:
  family:
    description: "Image family (repo folder name)."
    required: true
  distro:
    description: "Image distro/release."
    required: true
  metadata:
    description: "Newline/comma separated list of bake metadata JSON paths or directories."
    required: true
  extra-tag:
    description: "Optional suffix appended to each manifest tag (e.g., date or ref)."
    required: false
  docker-username:
    description: "Docker Hub username/organization."
    default: ${{ github.actor }}
    required: false
  docker-password:
    description: "Docker Hub password/token."
    required: false
  ghcr-username:
    description: "GHCR username/organization."
    default: ${{ github.repository_owner }}
    required: false
  ghcr-password:
    description: "GHCR password/token (use GITHUB_TOKEN)."
    required: false
  dry-run:
    description: "Do not execute docker imagetools create; print commands instead."
    default: "false"
    required: false

outputs:
  created-tags:
    description: "JSON map of stage -> tags pushed."
    value: ${{ steps.merge.outputs.created_tags }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: ${{ inputs.docker-password }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Log in to GHCR
      if: ${{ inputs.ghcr-password }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr-username }}
        password: ${{ inputs.ghcr-password }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.x"

    - name: Merge manifests
      id: merge
      shell: bash
      run: |
        set -euo pipefail
        cmd=(python .github/actions/docker-merge/merge_manifests.py
             --family "${{ inputs.family }}"
             --distro "${{ inputs.distro }}"
             --metadata-list "${{ inputs.metadata }}"
             ${{ inputs.ghcr-password && format('--gh-owner "{0}"', inputs.ghcr-username) || '' }}
             ${{ inputs.docker-password && format('--dockerhub-username "{0}"', inputs.docker-username) || '' }}
             ${{ inputs.extra-tag != '' && format('--extra-tag "{0}"', inputs.extra-tag) || '' }}
        )
        if [[ "${{ inputs.dry-run }}" == "true" ]]; then
          cmd+=(--dry-run)
        fi
        "${cmd[@]}"

    - name: Summary
      if: always()
      shell: bash
      run: |
        {
          echo "### Merge summary"
          echo "- Program: \`${{ inputs.family }}\`"
          echo "- Distro:  \`${{ inputs.distro }}\`"
          echo "- Metadata: \`${{ inputs.metadata }}\`"
          echo "- Created: \`${{ steps.merge.outputs.created_tags || 'n/a' }}\`"
        } >> "$GITHUB_STEP_SUMMARY"
