# Generated by generate.py from templates.yml — DO NOT EDIT BY HAND.

variable "REGISTRY" { default = "althack" }



target "ros2-rolling-base" {
  context    = "ros2"
  dockerfile = "rolling.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:rolling-base",
  ]
}

target "ros2-rolling-dev" {
  context    = "ros2"
  dockerfile = "rolling.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:rolling-dev",
  ]
}

target "ros2-rolling-full" {
  context    = "ros2"
  dockerfile = "rolling.Dockerfile"
  target     = "full"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:rolling-full",
  ]
}

target "ros2-rolling-gazebo" {
  context    = "ros2"
  dockerfile = "rolling.Dockerfile"
  target     = "gazebo"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:rolling-gazebo",
  ]
}

# ---- group per repo+release  ----
group "ros2-rolling" {
  targets = ["ros2-rolling-base", "ros2-rolling-dev", "ros2-rolling-full", "ros2-rolling-gazebo"]
}



target "ros2-rolling-cuda-base" {
  context    = "ros2"
  dockerfile = "rolling-cuda.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:rolling-cuda-base",
  ]
}

target "ros2-rolling-cuda-dev" {
  context    = "ros2"
  dockerfile = "rolling-cuda.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:rolling-cuda-dev",
  ]
}

target "ros2-rolling-cuda-full" {
  context    = "ros2"
  dockerfile = "rolling-cuda.Dockerfile"
  target     = "full"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:rolling-cuda-full",
  ]
}

target "ros2-rolling-cuda-gazebo" {
  context    = "ros2"
  dockerfile = "rolling-cuda.Dockerfile"
  target     = "gazebo"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:rolling-cuda-gazebo",
  ]
}

# ---- group per repo+release  ----
group "ros2-rolling-cuda" {
  targets = ["ros2-rolling-cuda-base", "ros2-rolling-cuda-dev", "ros2-rolling-cuda-full", "ros2-rolling-cuda-gazebo"]
}



target "ros2-kilted-base" {
  context    = "ros2"
  dockerfile = "kilted.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:kilted-base",
  ]
}

target "ros2-kilted-dev" {
  context    = "ros2"
  dockerfile = "kilted.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:kilted-dev",
  ]
}

target "ros2-kilted-full" {
  context    = "ros2"
  dockerfile = "kilted.Dockerfile"
  target     = "full"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:kilted-full",
  ]
}

target "ros2-kilted-gazebo" {
  context    = "ros2"
  dockerfile = "kilted.Dockerfile"
  target     = "gazebo"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:kilted-gazebo",
  ]
}

# ---- group per repo+release  ----
group "ros2-kilted" {
  targets = ["ros2-kilted-base", "ros2-kilted-dev", "ros2-kilted-full", "ros2-kilted-gazebo"]
}



target "ros2-jazzy-base" {
  context    = "ros2"
  dockerfile = "jazzy.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:jazzy-base",
  ]
}

target "ros2-jazzy-dev" {
  context    = "ros2"
  dockerfile = "jazzy.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:jazzy-dev",
  ]
}

target "ros2-jazzy-full" {
  context    = "ros2"
  dockerfile = "jazzy.Dockerfile"
  target     = "full"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:jazzy-full",
  ]
}

target "ros2-jazzy-gazebo" {
  context    = "ros2"
  dockerfile = "jazzy.Dockerfile"
  target     = "gazebo"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:jazzy-gazebo",
  ]
}

# ---- group per repo+release  ----
group "ros2-jazzy" {
  targets = ["ros2-jazzy-base", "ros2-jazzy-dev", "ros2-jazzy-full", "ros2-jazzy-gazebo"]
}



target "ros2-jazzy-cuda-base" {
  context    = "ros2"
  dockerfile = "jazzy-cuda.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:jazzy-cuda-base",
  ]
}

target "ros2-jazzy-cuda-dev" {
  context    = "ros2"
  dockerfile = "jazzy-cuda.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:jazzy-cuda-dev",
  ]
}

target "ros2-jazzy-cuda-full" {
  context    = "ros2"
  dockerfile = "jazzy-cuda.Dockerfile"
  target     = "full"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:jazzy-cuda-full",
  ]
}

target "ros2-jazzy-cuda-gazebo" {
  context    = "ros2"
  dockerfile = "jazzy-cuda.Dockerfile"
  target     = "gazebo"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:jazzy-cuda-gazebo",
  ]
}

# ---- group per repo+release  ----
group "ros2-jazzy-cuda" {
  targets = ["ros2-jazzy-cuda-base", "ros2-jazzy-cuda-dev", "ros2-jazzy-cuda-full", "ros2-jazzy-cuda-gazebo"]
}



target "ros2-humble-base" {
  context    = "ros2"
  dockerfile = "humble.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:humble-base",
  ]
}

target "ros2-humble-dev" {
  context    = "ros2"
  dockerfile = "humble.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:humble-dev",
  ]
}

target "ros2-humble-full" {
  context    = "ros2"
  dockerfile = "humble.Dockerfile"
  target     = "full"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:humble-full",
  ]
}

target "ros2-humble-gazebo" {
  context    = "ros2"
  dockerfile = "humble.Dockerfile"
  target     = "gazebo"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:humble-gazebo",
  ]
}

# ---- group per repo+release  ----
group "ros2-humble" {
  targets = ["ros2-humble-base", "ros2-humble-dev", "ros2-humble-full", "ros2-humble-gazebo"]
}



target "ros2-humble-cuda-base" {
  context    = "ros2"
  dockerfile = "humble-cuda.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:humble-cuda-base",
  ]
}

target "ros2-humble-cuda-dev" {
  context    = "ros2"
  dockerfile = "humble-cuda.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:humble-cuda-dev",
  ]
}

target "ros2-humble-cuda-full" {
  context    = "ros2"
  dockerfile = "humble-cuda.Dockerfile"
  target     = "full"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:humble-cuda-full",
  ]
}

target "ros2-humble-cuda-gazebo" {
  context    = "ros2"
  dockerfile = "humble-cuda.Dockerfile"
  target     = "gazebo"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ros2:humble-cuda-gazebo",
  ]
}

# ---- group per repo+release  ----
group "ros2-humble-cuda" {
  targets = ["ros2-humble-cuda-base", "ros2-humble-cuda-dev", "ros2-humble-cuda-full", "ros2-humble-cuda-gazebo"]
}



target "ignition-fortress-base" {
  context    = "ignition"
  dockerfile = "fortress.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ignition:fortress-base",
  ]
}

target "ignition-fortress-dev" {
  context    = "ignition"
  dockerfile = "fortress.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/ignition:fortress-dev",
  ]
}

# ---- group per repo+release  ----
group "ignition-fortress" {
  targets = ["ignition-fortress-base", "ignition-fortress-dev"]
}



target "gz-jetty-base" {
  context    = "gz"
  dockerfile = "jetty.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/gz:jetty-base",
  ]
}

target "gz-jetty-dev" {
  context    = "gz"
  dockerfile = "jetty.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/gz:jetty-dev",
  ]
}

# ---- group per repo+release  ----
group "gz-jetty" {
  targets = ["gz-jetty-base", "gz-jetty-dev"]
}



target "gz-jetty-cuda-base" {
  context    = "gz"
  dockerfile = "jetty-cuda.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/gz:jetty-cuda-base",
  ]
}

target "gz-jetty-cuda-dev" {
  context    = "gz"
  dockerfile = "jetty-cuda.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/gz:jetty-cuda-dev",
  ]
}

# ---- group per repo+release  ----
group "gz-jetty-cuda" {
  targets = ["gz-jetty-cuda-base", "gz-jetty-cuda-dev"]
}



target "gz-ionic-base" {
  context    = "gz"
  dockerfile = "ionic.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/gz:ionic-base",
  ]
}

target "gz-ionic-dev" {
  context    = "gz"
  dockerfile = "ionic.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/gz:ionic-dev",
  ]
}

# ---- group per repo+release  ----
group "gz-ionic" {
  targets = ["gz-ionic-base", "gz-ionic-dev"]
}



target "gz-ionic-cuda-base" {
  context    = "gz"
  dockerfile = "ionic-cuda.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/gz:ionic-cuda-base",
  ]
}

target "gz-ionic-cuda-dev" {
  context    = "gz"
  dockerfile = "ionic-cuda.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/gz:ionic-cuda-dev",
  ]
}

# ---- group per repo+release  ----
group "gz-ionic-cuda" {
  targets = ["gz-ionic-cuda-base", "gz-ionic-cuda-dev"]
}



target "gz-harmonic-base" {
  context    = "gz"
  dockerfile = "harmonic.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/gz:harmonic-base",
  ]
}

target "gz-harmonic-dev" {
  context    = "gz"
  dockerfile = "harmonic.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/gz:harmonic-dev",
  ]
}

# ---- group per repo+release  ----
group "gz-harmonic" {
  targets = ["gz-harmonic-base", "gz-harmonic-dev"]
}



target "gz-harmonic-cuda-base" {
  context    = "gz"
  dockerfile = "harmonic-cuda.Dockerfile"
  target     = "base"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/gz:harmonic-cuda-base",
  ]
}

target "gz-harmonic-cuda-dev" {
  context    = "gz"
  dockerfile = "harmonic-cuda.Dockerfile"
  target     = "dev"
  # Default platforms from templates.yml; override at runtime with --set <group>.*.platform=...
  tags       = [
    "${REGISTRY}/gz:harmonic-cuda-dev",
  ]
}

# ---- group per repo+release  ----
group "gz-harmonic-cuda" {
  targets = ["gz-harmonic-cuda-base", "gz-harmonic-cuda-dev"]
}



group "ros2-rolling-amd64" { targets = [ "ros2-rolling-base", "ros2-rolling-dev", "ros2-rolling-full", "ros2-rolling-gazebo" ] }

group "ros2-rolling-arm64" { targets = [ "ros2-rolling-base" ] }


group "ros2-rolling-cuda-amd64" { targets = [ "ros2-rolling-cuda-base", "ros2-rolling-cuda-dev", "ros2-rolling-cuda-full", "ros2-rolling-cuda-gazebo" ] }



group "ros2-kilted-amd64" { targets = [ "ros2-kilted-base", "ros2-kilted-dev", "ros2-kilted-full", "ros2-kilted-gazebo" ] }

group "ros2-kilted-arm64" { targets = [ "ros2-kilted-base" ] }


group "ros2-jazzy-amd64" { targets = [ "ros2-jazzy-base", "ros2-jazzy-dev", "ros2-jazzy-full", "ros2-jazzy-gazebo" ] }

group "ros2-jazzy-arm64" { targets = [ "ros2-jazzy-base" ] }


group "ros2-jazzy-cuda-amd64" { targets = [ "ros2-jazzy-cuda-base", "ros2-jazzy-cuda-dev", "ros2-jazzy-cuda-full", "ros2-jazzy-cuda-gazebo" ] }



group "ros2-humble-amd64" { targets = [ "ros2-humble-base", "ros2-humble-dev", "ros2-humble-full", "ros2-humble-gazebo" ] }

group "ros2-humble-arm64" { targets = [ "ros2-humble-base", "ros2-humble-dev", "ros2-humble-full" ] }


group "ros2-humble-cuda-amd64" { targets = [ "ros2-humble-cuda-base", "ros2-humble-cuda-dev", "ros2-humble-cuda-full", "ros2-humble-cuda-gazebo" ] }



group "ignition-fortress-amd64" { targets = [ "ignition-fortress-base", "ignition-fortress-dev" ] }



group "gz-jetty-amd64" { targets = [ "gz-jetty-base", "gz-jetty-dev" ] }



group "gz-jetty-cuda-amd64" { targets = [ "gz-jetty-cuda-base", "gz-jetty-cuda-dev" ] }



group "gz-ionic-amd64" { targets = [ "gz-ionic-base", "gz-ionic-dev" ] }



group "gz-ionic-cuda-amd64" { targets = [ "gz-ionic-cuda-base", "gz-ionic-cuda-dev" ] }



group "gz-harmonic-amd64" { targets = [ "gz-harmonic-base", "gz-harmonic-dev" ] }



group "gz-harmonic-cuda-amd64" { targets = [ "gz-harmonic-cuda-base", "gz-harmonic-cuda-dev" ] }



group "ros" { targets = [  ] }
group "ros2" { targets = [ "ros2-rolling-base", "ros2-rolling-dev", "ros2-rolling-full", "ros2-rolling-gazebo", "ros2-rolling-cuda-base", "ros2-rolling-cuda-dev", "ros2-rolling-cuda-full", "ros2-rolling-cuda-gazebo", "ros2-kilted-base", "ros2-kilted-dev", "ros2-kilted-full", "ros2-kilted-gazebo", "ros2-jazzy-base", "ros2-jazzy-dev", "ros2-jazzy-full", "ros2-jazzy-gazebo", "ros2-jazzy-cuda-base", "ros2-jazzy-cuda-dev", "ros2-jazzy-cuda-full", "ros2-jazzy-cuda-gazebo", "ros2-humble-base", "ros2-humble-dev", "ros2-humble-full", "ros2-humble-gazebo", "ros2-humble-cuda-base", "ros2-humble-cuda-dev", "ros2-humble-cuda-full", "ros2-humble-cuda-gazebo" ] }
group "gazebo" { targets = [  ] }
group "ignition" { targets = [ "ignition-fortress-base", "ignition-fortress-dev" ] }
group "gz" { targets = [ "gz-jetty-base", "gz-jetty-dev", "gz-jetty-cuda-base", "gz-jetty-cuda-dev", "gz-ionic-base", "gz-ionic-dev", "gz-ionic-cuda-base", "gz-ionic-cuda-dev", "gz-harmonic-base", "gz-harmonic-dev", "gz-harmonic-cuda-base", "gz-harmonic-cuda-dev" ] }

# ---- all non-EOL ----
group "default" {
  targets = [
    "ros2-rolling-base", "ros2-rolling-dev", "ros2-rolling-full", "ros2-rolling-gazebo", "ros2-rolling-cuda-base", "ros2-rolling-cuda-dev", "ros2-rolling-cuda-full", "ros2-rolling-cuda-gazebo", "ros2-kilted-base", "ros2-kilted-dev", "ros2-kilted-full", "ros2-kilted-gazebo", "ros2-jazzy-base", "ros2-jazzy-dev", "ros2-jazzy-full", "ros2-jazzy-gazebo", "ros2-jazzy-cuda-base", "ros2-jazzy-cuda-dev", "ros2-jazzy-cuda-full", "ros2-jazzy-cuda-gazebo", "ros2-humble-base", "ros2-humble-dev", "ros2-humble-full", "ros2-humble-gazebo", "ros2-humble-cuda-base", "ros2-humble-cuda-dev", "ros2-humble-cuda-full", "ros2-humble-cuda-gazebo", "ignition-fortress-base", "ignition-fortress-dev", "gz-jetty-base", "gz-jetty-dev", "gz-jetty-cuda-base", "gz-jetty-cuda-dev", "gz-ionic-base", "gz-ionic-dev", "gz-ionic-cuda-base", "gz-ionic-cuda-dev", "gz-harmonic-base", "gz-harmonic-dev", "gz-harmonic-cuda-base", "gz-harmonic-cuda-dev"
  ]
}