# Generated by generate.py from templates.yml — DO NOT EDIT BY HAND.

variable "REGISTRY" { default = "althack" }

 
# ----------- targets for ros2-rolling -----------

target "ros2-rolling-base" {
  context    = "ros2"
  dockerfile = "rolling.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/ros2:rolling-base",
  ]
}

target "ros2-rolling-dev" {
  context    = "ros2"
  dockerfile = "rolling.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/ros2:rolling-dev",
  ]
}

target "ros2-rolling-full" {
  context    = "ros2"
  dockerfile = "rolling.Dockerfile"
  target     = "full"
  tags       = [
    "${REGISTRY}/ros2:rolling-full",
  ]
}

target "ros2-rolling-gazebo" {
  context    = "ros2"
  dockerfile = "rolling.Dockerfile"
  target     = "gazebo"
  tags       = [
    "${REGISTRY}/ros2:rolling-gazebo",
  ]
}

# ---- group for all ros2-rolling  ----
group "ros2-rolling" {
  targets = ["ros2-rolling-base", "ros2-rolling-dev", "ros2-rolling-full", "ros2-rolling-gazebo"]
}

# ----------- targets for ros2-rolling-cuda -----------

target "ros2-rolling-cuda-base" {
  context    = "ros2"
  dockerfile = "rolling-cuda.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/ros2:rolling-cuda-base",
  ]
}

target "ros2-rolling-cuda-dev" {
  context    = "ros2"
  dockerfile = "rolling-cuda.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/ros2:rolling-cuda-dev",
  ]
}

target "ros2-rolling-cuda-full" {
  context    = "ros2"
  dockerfile = "rolling-cuda.Dockerfile"
  target     = "full"
  tags       = [
    "${REGISTRY}/ros2:rolling-cuda-full",
  ]
}

target "ros2-rolling-cuda-gazebo" {
  context    = "ros2"
  dockerfile = "rolling-cuda.Dockerfile"
  target     = "gazebo"
  tags       = [
    "${REGISTRY}/ros2:rolling-cuda-gazebo",
  ]
}

# ---- group for all ros2-rolling-cuda  ----
group "ros2-rolling-cuda" {
  targets = ["ros2-rolling-cuda-base", "ros2-rolling-cuda-dev", "ros2-rolling-cuda-full", "ros2-rolling-cuda-gazebo"]
}

# ----------- targets for ros2-kilted -----------

target "ros2-kilted-base" {
  context    = "ros2"
  dockerfile = "kilted.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/ros2:kilted-base",
  ]
}

target "ros2-kilted-dev" {
  context    = "ros2"
  dockerfile = "kilted.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/ros2:kilted-dev",
  ]
}

target "ros2-kilted-full" {
  context    = "ros2"
  dockerfile = "kilted.Dockerfile"
  target     = "full"
  tags       = [
    "${REGISTRY}/ros2:kilted-full",
  ]
}

target "ros2-kilted-gazebo" {
  context    = "ros2"
  dockerfile = "kilted.Dockerfile"
  target     = "gazebo"
  tags       = [
    "${REGISTRY}/ros2:kilted-gazebo",
  ]
}

# ---- group for all ros2-kilted  ----
group "ros2-kilted" {
  targets = ["ros2-kilted-base", "ros2-kilted-dev", "ros2-kilted-full", "ros2-kilted-gazebo"]
}

# ----------- targets for ros2-kilted-cuda -----------

target "ros2-kilted-cuda-base" {
  context    = "ros2"
  dockerfile = "kilted-cuda.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/ros2:kilted-cuda-base",
  ]
}

target "ros2-kilted-cuda-dev" {
  context    = "ros2"
  dockerfile = "kilted-cuda.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/ros2:kilted-cuda-dev",
  ]
}

target "ros2-kilted-cuda-full" {
  context    = "ros2"
  dockerfile = "kilted-cuda.Dockerfile"
  target     = "full"
  tags       = [
    "${REGISTRY}/ros2:kilted-cuda-full",
  ]
}

target "ros2-kilted-cuda-gazebo" {
  context    = "ros2"
  dockerfile = "kilted-cuda.Dockerfile"
  target     = "gazebo"
  tags       = [
    "${REGISTRY}/ros2:kilted-cuda-gazebo",
  ]
}

# ---- group for all ros2-kilted-cuda  ----
group "ros2-kilted-cuda" {
  targets = ["ros2-kilted-cuda-base", "ros2-kilted-cuda-dev", "ros2-kilted-cuda-full", "ros2-kilted-cuda-gazebo"]
}

# ----------- targets for ros2-jazzy -----------

target "ros2-jazzy-base" {
  context    = "ros2"
  dockerfile = "jazzy.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/ros2:jazzy-base",
  ]
}

target "ros2-jazzy-dev" {
  context    = "ros2"
  dockerfile = "jazzy.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/ros2:jazzy-dev",
  ]
}

target "ros2-jazzy-full" {
  context    = "ros2"
  dockerfile = "jazzy.Dockerfile"
  target     = "full"
  tags       = [
    "${REGISTRY}/ros2:jazzy-full",
  ]
}

target "ros2-jazzy-gazebo" {
  context    = "ros2"
  dockerfile = "jazzy.Dockerfile"
  target     = "gazebo"
  tags       = [
    "${REGISTRY}/ros2:jazzy-gazebo",
  ]
}

# ---- group for all ros2-jazzy  ----
group "ros2-jazzy" {
  targets = ["ros2-jazzy-base", "ros2-jazzy-dev", "ros2-jazzy-full", "ros2-jazzy-gazebo"]
}

# ----------- targets for ros2-jazzy-cuda -----------

target "ros2-jazzy-cuda-base" {
  context    = "ros2"
  dockerfile = "jazzy-cuda.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/ros2:jazzy-cuda-base",
  ]
}

target "ros2-jazzy-cuda-dev" {
  context    = "ros2"
  dockerfile = "jazzy-cuda.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/ros2:jazzy-cuda-dev",
  ]
}

target "ros2-jazzy-cuda-full" {
  context    = "ros2"
  dockerfile = "jazzy-cuda.Dockerfile"
  target     = "full"
  tags       = [
    "${REGISTRY}/ros2:jazzy-cuda-full",
  ]
}

target "ros2-jazzy-cuda-gazebo" {
  context    = "ros2"
  dockerfile = "jazzy-cuda.Dockerfile"
  target     = "gazebo"
  tags       = [
    "${REGISTRY}/ros2:jazzy-cuda-gazebo",
  ]
}

# ---- group for all ros2-jazzy-cuda  ----
group "ros2-jazzy-cuda" {
  targets = ["ros2-jazzy-cuda-base", "ros2-jazzy-cuda-dev", "ros2-jazzy-cuda-full", "ros2-jazzy-cuda-gazebo"]
}

# ----------- targets for ros2-humble -----------

target "ros2-humble-base" {
  context    = "ros2"
  dockerfile = "humble.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/ros2:humble-base",
  ]
}

target "ros2-humble-dev" {
  context    = "ros2"
  dockerfile = "humble.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/ros2:humble-dev",
  ]
}

target "ros2-humble-full" {
  context    = "ros2"
  dockerfile = "humble.Dockerfile"
  target     = "full"
  tags       = [
    "${REGISTRY}/ros2:humble-full",
  ]
}

target "ros2-humble-gazebo" {
  context    = "ros2"
  dockerfile = "humble.Dockerfile"
  target     = "gazebo"
  tags       = [
    "${REGISTRY}/ros2:humble-gazebo",
  ]
}

# ---- group for all ros2-humble  ----
group "ros2-humble" {
  targets = ["ros2-humble-base", "ros2-humble-dev", "ros2-humble-full", "ros2-humble-gazebo"]
}

# ----------- targets for ros2-humble-cuda -----------

target "ros2-humble-cuda-base" {
  context    = "ros2"
  dockerfile = "humble-cuda.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/ros2:humble-cuda-base",
  ]
}

target "ros2-humble-cuda-dev" {
  context    = "ros2"
  dockerfile = "humble-cuda.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/ros2:humble-cuda-dev",
  ]
}

target "ros2-humble-cuda-full" {
  context    = "ros2"
  dockerfile = "humble-cuda.Dockerfile"
  target     = "full"
  tags       = [
    "${REGISTRY}/ros2:humble-cuda-full",
  ]
}

target "ros2-humble-cuda-gazebo" {
  context    = "ros2"
  dockerfile = "humble-cuda.Dockerfile"
  target     = "gazebo"
  tags       = [
    "${REGISTRY}/ros2:humble-cuda-gazebo",
  ]
}

# ---- group for all ros2-humble-cuda  ----
group "ros2-humble-cuda" {
  targets = ["ros2-humble-cuda-base", "ros2-humble-cuda-dev", "ros2-humble-cuda-full", "ros2-humble-cuda-gazebo"]
}

# ----------- targets for ignition-fortress -----------

target "ignition-fortress-base" {
  context    = "ignition"
  dockerfile = "fortress.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/ignition:fortress-base",
  ]
}

target "ignition-fortress-dev" {
  context    = "ignition"
  dockerfile = "fortress.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/ignition:fortress-dev",
  ]
}

# ---- group for all ignition-fortress  ----
group "ignition-fortress" {
  targets = ["ignition-fortress-base", "ignition-fortress-dev"]
}

# ----------- targets for gz-jetty -----------

target "gz-jetty-base" {
  context    = "gz"
  dockerfile = "jetty.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/gz:jetty-base",
  ]
}

target "gz-jetty-dev" {
  context    = "gz"
  dockerfile = "jetty.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/gz:jetty-dev",
  ]
}

# ---- group for all gz-jetty  ----
group "gz-jetty" {
  targets = ["gz-jetty-base", "gz-jetty-dev"]
}

# ----------- targets for gz-jetty-cuda -----------

target "gz-jetty-cuda-base" {
  context    = "gz"
  dockerfile = "jetty-cuda.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/gz:jetty-cuda-base",
  ]
}

target "gz-jetty-cuda-dev" {
  context    = "gz"
  dockerfile = "jetty-cuda.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/gz:jetty-cuda-dev",
  ]
}

# ---- group for all gz-jetty-cuda  ----
group "gz-jetty-cuda" {
  targets = ["gz-jetty-cuda-base", "gz-jetty-cuda-dev"]
}

# ----------- targets for gz-ionic -----------

target "gz-ionic-base" {
  context    = "gz"
  dockerfile = "ionic.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/gz:ionic-base",
  ]
}

target "gz-ionic-dev" {
  context    = "gz"
  dockerfile = "ionic.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/gz:ionic-dev",
  ]
}

# ---- group for all gz-ionic  ----
group "gz-ionic" {
  targets = ["gz-ionic-base", "gz-ionic-dev"]
}

# ----------- targets for gz-ionic-cuda -----------

target "gz-ionic-cuda-base" {
  context    = "gz"
  dockerfile = "ionic-cuda.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/gz:ionic-cuda-base",
  ]
}

target "gz-ionic-cuda-dev" {
  context    = "gz"
  dockerfile = "ionic-cuda.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/gz:ionic-cuda-dev",
  ]
}

# ---- group for all gz-ionic-cuda  ----
group "gz-ionic-cuda" {
  targets = ["gz-ionic-cuda-base", "gz-ionic-cuda-dev"]
}

# ----------- targets for gz-harmonic -----------

target "gz-harmonic-base" {
  context    = "gz"
  dockerfile = "harmonic.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/gz:harmonic-base",
  ]
}

target "gz-harmonic-dev" {
  context    = "gz"
  dockerfile = "harmonic.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/gz:harmonic-dev",
  ]
}

# ---- group for all gz-harmonic  ----
group "gz-harmonic" {
  targets = ["gz-harmonic-base", "gz-harmonic-dev"]
}

# ----------- targets for gz-harmonic-cuda -----------

target "gz-harmonic-cuda-base" {
  context    = "gz"
  dockerfile = "harmonic-cuda.Dockerfile"
  target     = "base"
  tags       = [
    "${REGISTRY}/gz:harmonic-cuda-base",
  ]
}

target "gz-harmonic-cuda-dev" {
  context    = "gz"
  dockerfile = "harmonic-cuda.Dockerfile"
  target     = "dev"
  tags       = [
    "${REGISTRY}/gz:harmonic-cuda-dev",
  ]
}

# ---- group for all gz-harmonic-cuda  ----
group "gz-harmonic-cuda" {
  targets = ["gz-harmonic-cuda-base", "gz-harmonic-cuda-dev"]
}


# ---------- Parent-platform groups per entry (os/arch; variant-agnostic) ---------- #

group "ros2-rolling-linux-amd64" { targets = [ "ros2-rolling-base", "ros2-rolling-dev", "ros2-rolling-full", "ros2-rolling-gazebo" ] }
group "ros2-rolling-linux-arm64" { targets = [ "ros2-rolling-base" ] }


group "ros2-rolling-cuda-linux-amd64" { targets = [ "ros2-rolling-cuda-base", "ros2-rolling-cuda-dev", "ros2-rolling-cuda-full", "ros2-rolling-cuda-gazebo" ] }


group "ros2-kilted-linux-amd64" { targets = [ "ros2-kilted-base", "ros2-kilted-dev", "ros2-kilted-full", "ros2-kilted-gazebo" ] }
group "ros2-kilted-linux-arm64" { targets = [ "ros2-kilted-base" ] }


group "ros2-kilted-cuda-linux-amd64" { targets = [ "ros2-kilted-cuda-base", "ros2-kilted-cuda-dev", "ros2-kilted-cuda-full", "ros2-kilted-cuda-gazebo" ] }


group "ros2-jazzy-linux-amd64" { targets = [ "ros2-jazzy-base", "ros2-jazzy-dev", "ros2-jazzy-full", "ros2-jazzy-gazebo" ] }
group "ros2-jazzy-linux-arm64" { targets = [ "ros2-jazzy-base" ] }


group "ros2-jazzy-cuda-linux-amd64" { targets = [ "ros2-jazzy-cuda-base", "ros2-jazzy-cuda-dev", "ros2-jazzy-cuda-full", "ros2-jazzy-cuda-gazebo" ] }


group "ros2-humble-linux-amd64" { targets = [ "ros2-humble-base", "ros2-humble-dev", "ros2-humble-full", "ros2-humble-gazebo" ] }
group "ros2-humble-linux-arm64" { targets = [ "ros2-humble-base", "ros2-humble-dev", "ros2-humble-full" ] }


group "ros2-humble-cuda-linux-amd64" { targets = [ "ros2-humble-cuda-base", "ros2-humble-cuda-dev", "ros2-humble-cuda-full", "ros2-humble-cuda-gazebo" ] }


group "ignition-fortress-linux-amd64" { targets = [ "ignition-fortress-base", "ignition-fortress-dev" ] }


group "gz-jetty-linux-amd64" { targets = [ "gz-jetty-base", "gz-jetty-dev" ] }


group "gz-jetty-cuda-linux-amd64" { targets = [ "gz-jetty-cuda-base", "gz-jetty-cuda-dev" ] }


group "gz-ionic-linux-amd64" { targets = [ "gz-ionic-base", "gz-ionic-dev" ] }


group "gz-ionic-cuda-linux-amd64" { targets = [ "gz-ionic-cuda-base", "gz-ionic-cuda-dev" ] }


group "gz-harmonic-linux-amd64" { targets = [ "gz-harmonic-base", "gz-harmonic-dev" ] }


group "gz-harmonic-cuda-linux-amd64" { targets = [ "gz-harmonic-cuda-base", "gz-harmonic-cuda-dev" ] }


# ---------- Family-level groups (e.g., ros2, gz, ignition) ----------

group "ros" { targets = [  ] }
group "ros2" { targets = [ "ros2-rolling-base", "ros2-rolling-dev", "ros2-rolling-full", "ros2-rolling-gazebo", "ros2-rolling-cuda-base", "ros2-rolling-cuda-dev", "ros2-rolling-cuda-full", "ros2-rolling-cuda-gazebo", "ros2-kilted-base", "ros2-kilted-dev", "ros2-kilted-full", "ros2-kilted-gazebo", "ros2-kilted-cuda-base", "ros2-kilted-cuda-dev", "ros2-kilted-cuda-full", "ros2-kilted-cuda-gazebo", "ros2-jazzy-base", "ros2-jazzy-dev", "ros2-jazzy-full", "ros2-jazzy-gazebo", "ros2-jazzy-cuda-base", "ros2-jazzy-cuda-dev", "ros2-jazzy-cuda-full", "ros2-jazzy-cuda-gazebo", "ros2-humble-base", "ros2-humble-dev", "ros2-humble-full", "ros2-humble-gazebo", "ros2-humble-cuda-base", "ros2-humble-cuda-dev", "ros2-humble-cuda-full", "ros2-humble-cuda-gazebo" ] }
group "gazebo" { targets = [  ] }
group "ignition" { targets = [ "ignition-fortress-base", "ignition-fortress-dev" ] }
group "gz" { targets = [ "gz-jetty-base", "gz-jetty-dev", "gz-jetty-cuda-base", "gz-jetty-cuda-dev", "gz-ionic-base", "gz-ionic-dev", "gz-ionic-cuda-base", "gz-ionic-cuda-dev", "gz-harmonic-base", "gz-harmonic-dev", "gz-harmonic-cuda-base", "gz-harmonic-cuda-dev" ] }

# ---- all non-EOL ----
group "default" {
  targets = [
    "ros2-rolling-base", "ros2-rolling-dev", "ros2-rolling-full", "ros2-rolling-gazebo", "ros2-rolling-cuda-base", "ros2-rolling-cuda-dev", "ros2-rolling-cuda-full", "ros2-rolling-cuda-gazebo", "ros2-kilted-base", "ros2-kilted-dev", "ros2-kilted-full", "ros2-kilted-gazebo", "ros2-kilted-cuda-base", "ros2-kilted-cuda-dev", "ros2-kilted-cuda-full", "ros2-kilted-cuda-gazebo", "ros2-jazzy-base", "ros2-jazzy-dev", "ros2-jazzy-full", "ros2-jazzy-gazebo", "ros2-jazzy-cuda-base", "ros2-jazzy-cuda-dev", "ros2-jazzy-cuda-full", "ros2-jazzy-cuda-gazebo", "ros2-humble-base", "ros2-humble-dev", "ros2-humble-full", "ros2-humble-gazebo", "ros2-humble-cuda-base", "ros2-humble-cuda-dev", "ros2-humble-cuda-full", "ros2-humble-cuda-gazebo", "ignition-fortress-base", "ignition-fortress-dev", "gz-jetty-base", "gz-jetty-dev", "gz-jetty-cuda-base", "gz-jetty-cuda-dev", "gz-ionic-base", "gz-ionic-dev", "gz-ionic-cuda-base", "gz-ionic-cuda-dev", "gz-harmonic-base", "gz-harmonic-dev", "gz-harmonic-cuda-base", "gz-harmonic-cuda-dev"
  ]
}