#!/usr/bin/env python3
"""Generate the dockerfiles from a jinja template."""
from jinja2 import Environment, FileSystemLoader
from settings import templates
import logging

log = logging.getLogger(__name__)


def generate(log):
    """Generate the dockerfiles for this repo."""
    file_loader = FileSystemLoader('template')
    env = Environment(loader=file_loader)

    for repository in templates():
        # The jinja template file name
        template_file = repository + ".dockerfile.jinja"
        # The jinja template
        template = env.get_template(template_file)
        # The set of dockerfiles generated by this template
        dockerfiles = templates()[repository]
        for dockerfile in dockerfiles:
            output = template.render(dockerfile)
            out_file = repository + "/" + dockerfile['name'] + ".Dockerfile"
            log.info("Generating {filename}".format(filename=out_file))
            dockerfile_out = open(out_file, "w")
            dockerfile_out.write(output)
            dockerfile_out.close()
        log.info("Generating readme for {}".format(repository))
        readme_template = env.get_template('readme.md.jinja')
        readme_output = readme_template.render(
            {"repo_name": repository,
             "dockerfiles": dockerfiles})
        readme_file = repository + "/README.md"
        readme_out = open(readme_file, "w")
        readme_out.write(readme_output)
        readme_out.close()


if __name__ == "__main__":
    # Set up logger.
    log.setLevel(logging.INFO)
    formatter = logging.Formatter('%(message)s')
    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)
    ch.setFormatter(formatter)
    log.addHandler(ch)

    generate(log)
    log.info("Finished generating dockerfiles.")
