name: "Build & Push Docker images"
description: "Sets date, sets up QEMU/Buildx, logs into DockerHub + GHCR, then build-push with caching"
inputs:
  label:
    description: "Image label (repo folder name)"
    required: true
  tag:
    description: "Image tag (used in Dockerfile name and tags)"
    required: true
  target:
    description: "Dockerfile target stage"
    required: true
  platforms:
    description: "Comma-separated platforms list (e.g. linux/amd64,linux/arm64)"
    required: true
  docker-username: 
    description: "dockerhub username"
    default: ${{ github.actor }}
    required: false
  docker-password:
    description: "dockerhub password"
    required: false
  ghcr-username:
    description: "ghcr username"
    default: ${{ github.actor }}
    required: false
  ghcr-password:
    description: "ghcr password"
    required: false
  push:
    description: "Whether to push to docker"
    required: false
    default: "false"
  load:
    description: "Whether or not to load docker locally"
    required: false
    default: "false"
outputs:
  image:
     description: "Built image"
     value: ${{ steps.docker-build.outputs.imageid }}

runs:
  using: "composite"
  steps:
    - name: Set current date
      id: date
      shell: bash
      run: echo "date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"

    - name: Use current date
      shell: bash
      run: echo "Current date is ${{ steps.date.outputs.date }}"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: ${{ inputs.docker-password }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Log in to GHCR
      if: ${{ inputs.ghcr-password }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr-username }}
        password: ${{ inputs.ghcr-password }}

    - name: Build and push
      id: docker-build
      uses: docker/build-push-action@v6
      with:
        push: ${{ inputs.push }}
        file: ${{ inputs.label }}/${{ inputs.tag }}.Dockerfile
        context: ${{ inputs.label }}
        target: ${{ inputs.target }}
        platforms: ${{ inputs.platforms }}
        tags: |
          ${{ inputs.docker-username }}/${{ inputs.label }}:${{ inputs.tag }}-${{ inputs.target }}
          ${{ inputs.docker-username }}/${{ inputs.label }}:${{ inputs.tag }}-${{ inputs.target }}-${{ steps.date.outputs.date }}
          ghcr.io/${{ inputs.ghcr-username }}/${{ inputs.label }}:${{ inputs.tag }}-${{ inputs.target }}
        cache-from: |
          type=registry,ref=ghcr.io/${{ inputs.ghcr-username }}/${{ inputs.label }}:${{ inputs.tag }}-buildcache
        cache-to: ${{ inputs.push == 'true' && format('type=registry,ref=ghcr.io/{0}/{1}:{2}-buildcache,mode=max', inputs.ghcr-username, inputs.label, inputs.tag) || '' }}
        load: ${{ inputs.load }}
