name: "Build & Push Docker images"
description: "Sets date, sets up QEMU/Buildx, logs into DockerHub + GHCR, then build-push with caching"
inputs:
  label:
    description: "Image label (repo folder name)"
    required: true
  tag:
    description: "Image tag (used in Dockerfile name and tags)"
    required: true
  target:
    description: "Dockerfile target stage"
    required: true
  platforms:
    description: "Comma-separated platforms list (e.g. linux/amd64,linux/arm64)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set current date
      id: date
      shell: bash
      run: echo "date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"

    - name: Use current date
      shell: bash
      run: echo "Current date is ${{ steps.date.outputs.date }}"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: ${{ github.ref == 'refs/heads/main' }}
        file: ${{ inputs.label }}/${{ inputs.tag }}.Dockerfile
        context: ${{ inputs.label }}
        target: ${{ inputs.target }}
        platforms: ${{ inputs.platforms }}
        tags: |
          ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.label }}:${{ inputs.tag }}-${{ inputs.target }}
          ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.label }}:${{ inputs.tag }}-${{ inputs.target }}-${{ steps.date.outputs.date }}
          ghcr.io/${{ github.repository_owner }}/${{ inputs.label }}:${{ inputs.tag }}-${{ inputs.target }}
        cache-from: |
          type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ inputs.label }}:${{ inputs.tag }}-buildcache
        cache-to: |
          type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ inputs.label }}:${{ inputs.tag }}-buildcache,mode=max
