name: bot-jobs
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@1.0.0
        id: check
        with:
          trigger: "@athackst-bot autosquash"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions-ecosystem/action-add-labels@v1
        if: steps.check.outputs.triggered == 'true'
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          labels: autosquash
