name: push_dockerfiles

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - "kinetic"
          - "melodic"
          - "noetic"
          - "dashing"
          - "eloquent"
          - "foxy"
          - "blueprint"
          - "citadel"
          - "gazebo10"
          - "gazebo11"
          - "pages"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.1.2
        with:
          python-version: "3.x"
      - name: Build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          ./build.py ${{ matrix.docker_image }} --push --auth --verbose 

  readme:
    needs: docker
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    strategy:
      fail-fast: false
      matrix:
        docker_repo:
          - "ros"
          - "ros2"
          - "gazebo"
          - "ignition"
          - "github"
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: athackst/${{ matrix.docker_repo }}
          provider: dockerhub
          short_description: 'An assortment of development containers for ${{ matrix.docker_repo }}'
          readme_file: ${{ matrix.docker_repo }}/'README.md'